### ISSUE TITLE
Duplicate imports due to linked contacts for android

### ISSUE THREAD

**Issue by knyghtryda** [SunnyApp/flutter_contact#14]
Since flutter_contact (and contact_service) both use just the contact id on android they will pull in multiple contacts with the same id when contacts are linked.  Are there any issues using the lookupKey instead?  Anyone else here interested in this that would be willing to cooperate with me on a fix and a PR?

**Comment by ShRyDeR** [comment]
So you're saying contact.identifier is not unique?

**Comment by knyghtryda** [comment]
> So you're saying contact.identifier is not unique?

Actually the opposite.  Identifier on android currently points to each individual contact entry, which could be part of a linked contact.  If I pull id=1 and id=2 they could both point to Bob but one could just have an email address while the other could just have a phone number, or some other combination.  LookupKey should bring in the agragate contact (at least that's my read on it).

**Comment by ericmartineau** [comment]
I'm reading up on this today.  If you have any more insight, I'd love to hear it.

**Comment by ericmartineau** [comment]
@knyghtryda For Android, this library is based on `Contacts`, not `RawContacts`.  `Contacts` are the result of aggregating one or more `RawContact`.  If you had 3 contacts (RawContact) that were linked together into 1 `Contact`, the plugin would only return a single record. 

Lookup keys are useful in that they can help locate a previously existing record that "moved" as a result of being aggregated into another contact, or due to a fresh sync, eg. the google provider may resync all records if it deems the current data set to be corrupt.  This process would result in previously synced data getting a new `RAW_CONTACT_ID` and `CONTACT_ID`.

The lookup key helps in this scenario because you can look up a contact by `CONTACT_ID`, and also provide a lookup key as a fallback.  If the `CONTACT_ID` doesn't find any matches, then lookup key will attempt to find the new record (in this case, it would be the aggregate contact or the fresh sync copy.

After reading, I don't think it's a good idea to use lookup key as the primary key because it doesn't appear to be a durable value, nor is it a 1:1 identifier for a contact record.  There could be many different lookup keys that resolve to the same `CONTACT_ID`.

This question did raise a good point though, which is that there is no way to access raw vs aggregate contacts.  I made a change that essentially forks the contact service into to identical services - one that operates on `Contacts` and one that operators on `RawContacts`.  The `Contacts` global will point at the `AggregateContacts` instance, but you can also access `RawContacts` if you want to see all the linked data.
