### ISSUE TITLE
getContactsForPhone equivalent

### ISSUE THREAD

**Issue by ghenry** [SunnyApp/flutter_contact#21]
Hi,

I'm coming from https://github.com/lukasgit/flutter_contacts/ and I am using:

https://github.com/lukasgit/flutter_contacts/blob/master/android/src/main/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java#L103

Do you have a way to search partial contact numbers for type ahead search? Only full matches seem to be supported https://github.com/lukasgit/flutter_contacts/issues/147

**Comment by ericmartineau** [comment]
Which platform are you using?  The full-text search capabilities are limited by the platforms themselves - though there may be a different way to build those queries.

I've built and published another library `full_text_search` that does in-memory full-text searches.  Since this library (attempts) being memory efficient, it should _work_, though might be a little slow as it pages through results.

```
Future<Iterable<Contact>> _searchContacts(String term) async {
    final filtered = FullTextSearch<Contact>.ofStream(
      term: term,
      items: _contactService.streamContacts(),
      tokenize: (contact) {
        return [
          contact.givenName,
          contact.familyName,
          ...contact.phones
              .expand((number) => tokenizePhoneNumber(number.value)),
        ];
      },
    );
    return await filtered.items.toList();
  }
```

Disclaimer (I haven't tested this code).
