### ISSUE TITLE
Feature addition

### ISSUE THREAD

**Issue by hassanrehman01398** [SunnyApp/flutter_contact#36]
Query by number can be added in this repo

**Comment by ericmartineau** [comment]
by phone number?

**Comment by hassanrehman01398** [comment]
Query by username is added in the code so we can also add feature where we can run search by number too

**Comment by ericmartineau** [comment]
Phone number search support is not very consistent between ios and Android.  Personally, I use another package I wrote for doing in-memory full-text searches `full_text_search`.  If you look in the example for `flutter_contact` you can see how it's done.

I know there are options for phone search in the API.  I'll probably remove those in future releases though because I don't really like how the native search functions.  That said, I'm always open to a convincing argument...
